        Data Science: A Programming Approach
        Mahyar S Vaghefi
        University of Texas Arlington

<h1 align='center' style="color: blue;">Assignment #1</h1>

<p><b>Question #1</b>: 
    
<ol>
    <li> Write a small program that asks for an integer number from the user and print all the prime numbers (2,3,5,7,etc) less than the inputed number.</li>
    <li> How long it takes for your program to print the prime numbers less than 100. (Use magic functions) </li>
    </p>  

In [1]:
# Write your answer here (part1)
x=int(input("enter a number:"))
for Number in range (1,x):
    count = 0
    for i in range(2, (Number//2 + 1)):
        if(Number % i == 0):
            count = count + 1
            break

    if (count == 0 and Number != 1):
        print(" %d" %Number, end = '  ')

enter a number:55
 2   3   5   7   11   13   17   19   23   29   31   37   41   43   47   53  

In [2]:
%%timeit -n1 -r1
    for Number in range (2, 101):
        
        isPrime = True
        for i in range(2, Number):
            if(Number % i == 0):
                isPrime = False
                break
            
        if(isPrime):
            print(" %d" %Number, end = '  ')
            
    print("\n")

 2   3   5   7   11   13   17   19   23   29   31   37   41   43   47   53   59   61   67   71   73   79   83   89   97  

627 µs ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


<p><b>Question #2</b>: Write a small program that asks for two sentences from the user and returns a set of common words between two sentences.</p>
<p><u>Here is an example:</u><br>
Please input your first sentence: Hello, this is my first sentence<br>
Please input your second sentence: Ok, here is my second sentence<br>
    
{'is', 'my', 'sentence'}
</p>

In [3]:
# Write your answer here
sentence1 = input("enter your first sentence :")
sentence2 = input("enter your second sentence :")

sentence1_words = sentence1.split()
sentence2_words = sentence2.split()

common = set(sentence1_words).intersection( set(sentence2_words) )
unique = set(sentence1_words).symmetric_difference( set(sentence2_words) )

print (common)


enter your first sentence :ha ja ka ia
enter your second sentence :ha ia kak jaja
{'ia', 'ha'}


<p><b>Question #3</b>: The following dictionary provides information about employees of a company. The keys are tuples containing individuals' name, gender and birth year. The values are individiuals' salary. Write a code that removes female employees or those with birth year before 1987 from the dictionary.

employee_dict = {<br>
    ('John', 'male', 1986) : 130000,<br>
    ('Jane', 'female', 1983) : 110000,<br>
    ('Mona', 'female', 1989): 135000,<br>
    ('Emma', 'female', 1987): 88000,<br>
    ('Mark', 'male', 1983): 109000,<br>
    ('Alex', 'male', 1991): 117000,<br>
    ('Hanna', 'female', 1980): 123000<br>
}<br>
</p>

In [4]:
# Write your answer here
employee_dict = {
('John', 'male', 1986) : 130000,
('Jane', 'female', 1983) : 110000,
('Mona', 'female', 1989): 135000,
('Emma', 'female', 1987): 88000,
('Mark', 'male', 1983): 109000,
('Alex', 'male', 1991): 117000,
('Hanna', 'female', 1980): 123000
}

to_remove=[]
for key,value in employee_dict.items():
    if key[2]<1987 or  key[1]=='female':
        to_remove.append(key)
        
for key in to_remove:
     del employee_dict[key]

employee_dict

{('Alex', 'male', 1991): 117000}

<p><b>Question #4</b>:<br> 
<ol>
<li> Create a 3x5 random matrix using normal distribution with mean = 2 and std = .5 (matrix A)</li>
<li> Create another 5x3 matrix in the following format: (matrix B) 
<br>
<br>
<div>
<table style="width:200px; border:1px solid black">
<tr>
    <td style="text-align:center; border:1px solid black">1</td>
    <td style="text-align:center; border:1px solid black">0</td>
    <td style="text-align:center; border:1px solid black">2</td>
</tr>
<tr>
    <td style="text-align:center; border:1px solid black">3</td>
    <td style="text-align:center;border:1px solid black">4</td>
    <td style="text-align:center;border:1px solid black">1</td>
</tr>
<tr>
    <td style="text-align:center; border:1px solid black">-1</td>
    <td style="text-align:center; border:1px solid black">2</td>
    <td style="text-align:center;border:1px solid black">-3</td>
</tr>
<tr>
    <td style="text-align:center; border:1px solid black">5</td>
    <td style="text-align:center; border:1px solid black">4</td>
    <td style="text-align:center; border:1px solid black">0</td>
</tr>
<tr>
    <td style="text-align:center;border:1px solid black">0</td>
    <td style="text-align:center;border:1px solid black">0</td>
    <td style="text-align:center;border:1px solid black">2</td>
</tr>
</table>
<div></li>
   
<li> Find Dot Product of matrix A and B and put it in matrix C.</li>
<li> Find the column wise sum of the matrix C.</li> 
</p>


In [5]:
# Write your answer here (part1)
import numpy as np
Matrix_A = np.random.normal(loc = 2, scale = .5, size = (3,5))
print(Matrix_A)

[[1.56438417 2.8461291  1.34651489 1.2906314  1.37444341]
 [2.58723184 1.5432191  2.20074333 1.75588834 2.41794141]
 [2.94258257 1.50494515 1.90311524 2.00368983 2.3670222 ]]


In [6]:
# Write your answer here (part2)
import numpy as np
Matrix_B = np.array([[1, 0, 2],[3, 4, 1],[-1, 2, 3],[5,  4, 0],[0,  0, 2]])    
print(Matrix_B)

[[ 1  0  2]
 [ 3  4  1]
 [-1  2  3]
 [ 5  4  0]
 [ 0  0  2]]


In [7]:
# Write your answer here (part3)
Matrix_C=np.dot(Matrix_A,Matrix_B)
print(Matrix_C)


[[15.20941359 19.24007179 12.76332892]
 [13.79558749 17.59791639 18.15579557]
 [15.57275194 17.8407704  17.8335004 ]]


In [8]:
# Write your answer here (part4)
print("Column-wise sum: ", Matrix_C.sum(axis = 0))


Column-wise sum:  [44.57775302 54.67875858 48.75262488]


<p><b>Question #5</b>:<br> 
<ol> 
    <li>Create a random 5x5 matrix using discrete uniform integers between [0, 100) (matrix A) </li>
    <li>Use Boolean Indexing (Filtering) to subtract 15 from all the values over 60 in matrix A </li>
</ol> 
</p>

In [9]:
# Write your answer here (part1)
import numpy as np
rows  = 5
cols = 5
low = 0
high = 100
step = 2

matrix = np.random.choice([x for x in range(low,high,step)],rows*cols)
matrix.resize(rows,cols)

print(matrix)

[[58  6  6 30 34]
 [56 72 18 76 12]
 [ 8 52 38 36 42]
 [86 90 96 72 98]
 [38 48 58 42 66]]


In [10]:
# Write your answer here (part2)
import numpy as np
lol = np.where(matrix >60, matrix-15, matrix)
print(lol)

[[58  6  6 30 34]
 [56 57 18 61 12]
 [ 8 52 38 36 42]
 [71 75 81 57 83]
 [38 48 58 42 51]]


<p><b>Question #6</b>:<br> 
<ol>
<li> Use pandas read_csv( ) function to read the BlackFriday.csv file - You can find the csv file in Blackboard. (<b>Note:</b> This is a dataset available in Kaggle. It is a dataset of 550000 observations about the black Friday in a retail store, it contains different kinds of variables either numerical or categorical. It contains missing values.)</li>
<li> Find the number of male and female in this dataset </li>
<li> Find the average purchase amount by individuals' gender </li>
<li> Find the average purchase amount by age and gender (<b>Hint:</b> you need to use group by with multiple item) </li>
<li> Find the maximum purchase amount by age and city category and sort the result by the maximum purchase amount (ascending) </li>
<li> Find the minimum purchase amount by gender and marital status and sort the result by the maximum purchase amount (descending) </li>
</p>

In [11]:
# Write your answer here (part1)
import pandas as pd
data = pd.read_csv(r'C:\Users\sahej_surface\Downloads\Data Science\BlackFriday.csv')
data_dataframe=pd.DataFrame(data)

In [12]:
# Write your answer here (part2)
Gender=data_dataframe.Gender

females=0
males=0
for i in Gender:
    if i == "M":
        males += 1
    else:
        females += 1
print("number of Males = ",males)
print("number of Females = ",females)

number of Males =  405380
number of Females =  132197


In [13]:
# Write your answer here (part3)avg_purchase=data_dataframe.Purchase

avg_purchase_male=data_dataframe["Purchase"][data_dataframe["Gender"]=="M"].mean()
avg_purchase_female=data_dataframe["Purchase"][data_dataframe["Gender"]=="F"].mean()

print("Average purchase buy males = ", avg_purchase_male)

print("Average purchase buy males = ",avg_purchase_female)

Average purchase buy males =  9504.771712960679
Average purchase buy males =  8809.761348593387


In [14]:
# Write your answer here (part4)
avg_purchase_male_age = data_dataframe.groupby(["Gender","Age"])["Purchase"].mean().reset_index()

print(avg_purchase_male_age)


   Gender    Age     Purchase
0       F   0-17  8444.703210
1       F  18-25  8405.430852
2       F  26-35  8791.798654
3       F  36-45  9046.573808
4       F  46-50  8929.448740
5       F  51-55  9131.451837
6       F    55+  9119.577196
7       M   0-17  9312.322227
8       M  18-25  9506.501081
9       M  26-35  9470.621052
10      M  36-45  9517.126321
11      M  46-50  9429.151563
12      M  51-55  9789.020476
13      M    55+  9557.058094


In [15]:
# Write your answer here (part5)
avg_purchase_max_city = data_dataframe.groupby(["City_Category","Age"])["Purchase"].max().reset_index()
print(avg_purchase_max_city)

   City_Category    Age  Purchase
0              A   0-17     23847
1              A  18-25     23958
2              A  26-35     23961
3              A  36-45     23949
4              A  46-50     23912
5              A  51-55     23960
6              A    55+     23913
7              B   0-17     23953
8              B  18-25     23958
9              B  26-35     23955
10             B  36-45     23960
11             B  46-50     23960
12             B  51-55     23959
13             B    55+     23954
14             C   0-17     23955
15             C  18-25     23952
16             C  26-35     23961
17             C  36-45     23949
18             C  46-50     23919
19             C  51-55     23958
20             C    55+     23960


In [16]:
# Write your answer here (part6)
avg_purchase_min_MS = data_dataframe.groupby(["Gender","Marital_Status"])["Purchase"].min().reset_index()
print(avg_purchase_min_MS)

  Gender  Marital_Status  Purchase
0      F               0       185
1      F               1       186
2      M               0       185
3      M               1       187


<p><b>Question #7</b>:<br> 
<ol>
    <li>Consider the following two tables. Use lists, dictionaries and/or other Pandas data structure to create a separate DataFrame for each table.
    <div><br><br>
        <table style='width:400px; background-color:rgba(255,255,255,1)'>
            <tr style="background-color:rgba(255,255,255,1)">
                <th style='text-align:center' colspan='2'>product</th>
                <th></th>
                <th style='text-align:center' colspan='3'>availability</th>
            </tr>
            <tr style="background-color:rgba(255,255,255,1)">
                <td style='border:1px solid black'>product_id</td>
                <td style='border:1px solid black'>price</td>
                <td>&nbsp;</td>
                <td style='border:1px solid black'>product_id</td>
                <td style='border:1px solid black'>City</td>
                <td style='border:1px solid black'>Quantity</td>
            </tr>
            <tr style="background-color:rgba(255,255,255,1)">
                <td style='border:1px solid black'>A11</td>
                <td style='border:1px solid black'>22</td>
                <td>&nbsp;</td>
                <td style='border:1px solid black'>A11</td>
                <td style='border:1px solid black'>A</td>
                <td style='border:1px solid black'>21</td>
            </tr>
            <tr style="background-color:rgba(255,255,255,1)">
                <td style='border:1px solid black'>A12</td>
                <td style='border:1px solid black'>23</td>
                <td>&nbsp;</td>
                <td style='border:1px solid black'>A11</td>
                <td style='border:1px solid black'>B</td>
                <td style='border:1px solid black'>18</td>
            </tr>
            <tr style="background-color:rgba(255,255,255,1)">
                <td style='border:1px solid black'>A13</td>
                <td style='border:1px solid black'>14</td>
                <td>&nbsp;</td>
                <td style='border:1px solid black'>A11</td>
                <td style='border:1px solid black'>C</td>
                <td style='border:1px solid black'>17</td>
            </tr>
            <tr style="background-color:rgba(255,255,255,1)">
                <td style='border:1px solid black'>A14</td>
                <td style='border:1px solid black'>30</td>
                <td>&nbsp;</td>
                <td style='border:1px solid black'>A12</td>
                <td style='border:1px solid black'>B</td>
                <td style='border:1px solid black'>6</td>
            </tr>
            <tr style="background-color:rgba(255,255,255,1)">
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td style='border:1px solid black'>A12</td>
                <td style='border:1px solid black'>C</td>
                <td style='border:1px solid black'>2</td>
            </tr>
            <tr style="background-color:rgba(255,255,255,1)">
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td style='border:1px solid black'>A14</td>
                <td style='border:1px solid black'>A</td>
                <td style='border:1px solid black'>8</td>
            </tr>
            <tr style="background-color:rgba(255,255,255,1)">
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td style='border:1px solid black'>A14</td>
                <td style='border:1px solid black'>B</td>
                <td style='border:1px solid black'>10</td>
            </tr>
            <tr style="background-color:rgba(255,255,255,1)">
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td style='border:1px solid black'>A14</td>
                <td style='border:1px solid black'>D</td>
                <td style='border:1px solid black'>7</td>
            </tr>
        <table>
    </div>
    </li>
        <li>Merge two tables (use inner join)</li>
        <li>Merge two tables (use outer join)</li>
</ol>

In [17]:
# Write your answer here (part1)
import pandas as pd
df1 = pd.DataFrame({'product_id':['A11','A12','A13','A14'],
                    'price':['22','23','14','30']})
df2 = pd.DataFrame({'product_id':['A11','A11','A11','A12','A12','A13','A14','A14',],
                    'City':['A','B','C','B','C','A','B','D'],
                    'Quantity':['21','18','17','6','2','8','10','7']})
print(df1)
print(df2)

  product_id price
0        A11    22
1        A12    23
2        A13    14
3        A14    30
  product_id City Quantity
0        A11    A       21
1        A11    B       18
2        A11    C       17
3        A12    B        6
4        A12    C        2
5        A13    A        8
6        A14    B       10
7        A14    D        7


In [18]:
# Write your answer here (part2)
df3=pd.merge(df1,df2)
pd.merge(df1,df2 ,how='inner')

product_id price City Quantity
0        A11    22    A       21
1        A11    22    B       18
2        A11    22    C       17
3        A12    23    B        6
4        A12    23    C        2
5        A13    14    A        8
6        A14    30    B       10
7        A14    30    D        7

In [19]:
# Write your answer here (part3)

df3=pd.merge(df1,df2)
pd.merge(df1,df2 ,how='outer')

product_id price City Quantity
0        A11    22    A       21
1        A11    22    B       18
2        A11    22    C       17
3        A12    23    B        6
4        A12    23    C        2
5        A13    14    A        8
6        A14    30    B       10
7        A14    30    D        7

<p><b>Output</b>: 
    <ul>
        <li>You need to provide answers in the designated cell for each question (don't delete the existing comments in the cells).</li>
        <li>You need to make sure that your final file contains both codes and results (don't clear the outputs).</li>
        <li>Save your file in the .ipynb format (as it is right now).</li>
        <li>Create a zip-folder and put your file in it.</li>
        <li>Upload the zip-folder into Canvas (Assignment #1)</li>
        <li>All the assignments should be submitted by <b>Mon Sep 30 at 7:00 PM</b>. No late submission will be accepted</li>
        <li>I will not accept any submission by email or any other method, so make sure that you submit the file in a right place at a right time.</li>
        </ul>
        </p> 